version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: notifications-db
    environment:
      POSTGRES_DB: notifications
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"